### ISSUE TITLE
how we can download historical gfs data for visualization

### ISSUE THREAD

**Issue by aminabvaal** [cambecc/earth#102]
in this URL(`https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl`) we just have  recent 10 days passed and there is no more day to get data for before them 
for example i want some day in 2017 historically , it is ok in `https://earth.nullschool.net/` and how you can solved this problem

![image](https://user-images.githubusercontent.com/31241289/67643743-eeff5200-f92f-11e9-954f-cc590fa868d7.png)

**Comment by cambecc** [comment]
You might want to look here: https://nomads.ncdc.noaa.gov/data/gfsanl/
