### ISSUE TITLE
extract subregion - latitude is rending upside-down

### ISSUE THREAD

**Issue by hbriga** [cambecc/earth#123]
Hi everyone. I am trying to load wind data for the USA sub-region into earth and the result is not quite good. Extracted grib2 file from NOOA site, grib2json and load it. The original grib file is rending ok with other sw like xygrib. But on earth, latitude is rending the wrong way. Any idea of what I am doing wrong? Please see below print-screen from earth, xygrib, parameters at NOOA and original grib file with txt extension (rename it to grib2). Thanks for helping. 
Hélcio
 

![1  wind-USA-gfs-earth](https://user-images.githubusercontent.com/19753691/126047981-61c861f7-d6bb-494c-8d7f-1d83f6496b14.png)
![2  wind-USA-gfs-xygrib](https://user-images.githubusercontent.com/19753691/126047982-ac5ce822-a551-44ef-a9e5-74754cecf55e.png)
![3  extraction parameters](https://user-images.githubusercontent.com/19753691/126047986-8dc8499c-2f75-4bfc-b74d-24efa7b9b909.png)
[4. gfs.t00z.pgrb2.1p00.f000-GRIB_file.txt](https://github.com/cambecc/earth/files/6835220/4.gfs.t00z.pgrb2.1p00.f000-GRIB_file.txt)

**Comment by cambecc** [comment]
That looks like the lat coord needs to be mirrored along 25° N. Lon looks correct!

**Comment by hbriga** [comment]
Thank you Cameron. You are saying that it needs some preparation in the grib file before converting it to json, is that right?

**Comment by cambecc** [comment]
I'm not sure where things are going wrong, but it sure looks like the renderer thinks the data starts at 25°N and grows southward when it actually grows northward. If you open the json file and flip the sign of the "dy" field, it will probably work!

**Comment by hbriga** [comment]
yep, it worked indeed. thank you man.  I am working with local Brazilian gribs, which covers only the region. So, this issue first appears there. Now i can move forward.  I will close the issue here. Once again, thank you for your help.
