### ISSUE TITLE
.epak files vs json

### ISSUE THREAD

**Issue by smmotley** [cambecc/earth#30]
I stumbled upon your grib2json utility from this project and it has been a tremendous help. 

This project’s (i.e. "earth") facebook page stated that you recently switched from the GFS resolution of 1.0 deg to 0.5 deg, which surprised me due to the dramatic increase in the size that I assumed would occur in the json files. However, it appears as though you’ve overcome this through a format called .epak? Is the epak format something that you developed, or is this a part of the THREDDS project? I have searched for any information, but I’m not sure how you’re getting the grib2 files into this format. Any info you could provide would be greatly appreciated.

**Comment by cambecc** [comment]
The .epak format is a custom binary format. It's not a part of THREDDS. For the moment, I've decided not to release it under an open source license. That may change in the future.

**Comment by likev** [comment]
Is .epak format better than gzip compression ?

**Comment by nivs1978** [comment]
Any chance the epak files will be open source?
