### ISSUE TITLE
Pulling data from NOAA

### ISSUE THREAD

**Issue by jtippman** [cambecc/earth#32]
Hi

I am trying to pull new data. I execute this command:

    curl "http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs.pl?file=gfs.t00z.pgrbf00.grib2&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&dir=%2Fgfs.2015071200" -o gfs.t00z.pgrbf00.grib2

The file I am retrieving contains this:

> <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html><head><title>data file is not present; /common/data/model/com/gfs/prod/gfs.2015071200/gfs.t00z.pgrbf00.grib2</title></head><body bgcolor="#ffffff"><p align=center>Data file is not present: /common/data/model/com/gfs/prod/gfs.2015071200/gfs.t00z.pgrbf00.grib2</p><p align=left><small>g2sub 1.1.0.beta-6 and comments: Wesley.Ebisuzaki@noaa.gov, Jun.Wang@noaa.gov<br></small></body></html>

Am I doing something wrong in the link? 

Further, when I go to the directory http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs.pl and click on a file link with the July 12th date it says no file or directory is available. 

This one works: http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl, but just changing this in the above command still does not download an appropriate file.

It seems there are new links but I am not sure what file is appropriate (it seems there is a whole list of new files to choose from).

Any guidance or feedback would be great!

Thanks,
Jeff

**Comment by cambecc** [comment]
The NWS changed the file name format back in January. What if you try `gfs.t00z.pgrb2.1p00.f000` instead of `gfs.t00z.pgrbf00.grib2`?

**Comment by jtippman** [comment]
That worked. Thanks!

    curl "http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?file=gfs.t00z.pgrb2.1p00.f000&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&dir=%2Fgfs.2015071200" -o gfs.t00z.pgrb2.1p00.f000
    grib2json -d -n -o current-wind-surface-level-gfs-1.0.json gfs.t00z.pgrb2.1p00.f000

**Comment by AndreaAstronaut** [comment]
Hi,

did the file name change again?
With the following url:
http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs.pl?file=gfs.t00z.pgrb2.1p00.f000&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&dir=%2Fgfs.2016091300

I get the following:
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html><head><title>Error</title></head><body bgcolor="#ffffff"><font color=red><h2 align="center">Error</h2></font>
<p align="center"> Filename does not match legal pattern: gfs.t\d{2}z.pgrbf\d{2,3}.grib2$
<p align=left><small>g2sub 1.1.0.beta-6 and comments: Wesley.Ebisuzaki@noaa.gov, Jun.Wang@noaa.gov<br></small></body></html>

However, the following link does seem to work, so the file name seems ok:
http://www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.2016091300/gfs.t00z.pgrb2.1p00.f000

If I follow the legal file name suggested:
http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs.pl?file=gfs.t18z.pgrbf00.grib2&lev_500_mb=on&lev_700_mb=on&lev_1000_mb=on&var_HGT=on&dir=%2Fgfs.2013091300

Then i get:
Data file is not present: /common/data/model/com/gfs/prod/gfs.2013091300/gfs.t18z.pgrbf00.grib2

Am I doing something wrong?
