### ISSUE TITLE
Working with high resolution data

### ISSUE THREAD

**Issue by samuel2008** [cambecc/earth#50]
Hi,

I have high resolution wind data I'd like to display on the nullschool map.  My issue is that it's not in grib format so converting it using grib2json isn't an option.

What I'm hoping is that I can reverse engineer the .json data file using my high resolution wind data.

My question is whether there is anything that needs to be modified in the code itself to handle the high resolution data - for example, are there sections in the code that are hard-coded to only handle 1 degree resolution data? Or, do I just need to modify certain fields in the header sections of the json file i.e.:

numberPoints
nx
ny
lo1
la1
lo2
la2
dx
dy

I know what the above refer to, however I'm not exactly sure if the following need to be modified:

gribLength
resolution

Thanks for any insight you may have!!! Love this tool..

Sam

**Comment by samuel2008** [comment]
One addition..

I went the reverse engineering route with 0.25 degree GFS wind data and I'm getting an offset of around 110 degrees in longitude when plotting the data I produced on the map.  The latitude appears to be exactly correct.

I read the following post and my latitudes and longitudes follow the same orientation as discussed:

https://github.com/cambecc/grib2json/issues/10

Thanks
Sam

**Comment by thoglen** [comment]
Sam, did you figure this out? If so, what did you have to do to make it work?

**Comment by samuel2008** [comment]
So it turns out I was doing it right and it was just a cache issue! : )

Closing this now..

Thanks!
Sam
