### ISSUE TITLE
Future forecast

### ISSUE THREAD

**Issue by kaifaty** [cambecc/earth#56]
Where are you get future forecast data? [nomads.ncep.noaa.gov](http://nomads.ncep.noaa.gov/) allows download only present or past data.

**Comment by cambecc** [comment]
Each run contains several days of forecast data. Take a look here at the files containing the pattern FFF: http://www.nco.ncep.noaa.gov/pmb/products/gfs/

**Comment by agktogether** [comment]
@cambecc  thanks Great Man
